// <auto-generated />
namespace TrashCollector.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedtouseraddressgenerationmethodstoviewandcustomercontroller : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedtouseraddressgenerationmethodstoviewandcustomercontroller));
        
        string IMigrationMetadata.Id
        {
            get { return "201807141505321_added to useraddress generation methods to view and customercontroller"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
