// <auto-generated />
namespace TrashCollector.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addingdaymodeltodatabase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingdaymodeltodatabase));
        
        string IMigrationMetadata.Id
        {
            get { return "201807170042485_adding day model to database"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
